---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch Curator and required dependencies.
  pip:
    name: elasticsearch-curator
    version: "{{ elasticsearch_curator_version }}"

- name: Install Elasticsearch Curator required dependencies.
  pip: "name={{ item }}"
  with_items:
    - argparse

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
